name: "CI"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v10
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: domenkozar
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: cachix use iohk
    - run: nix-build ci.nix
